food_advisor/urls.py
from django.urls import path
from food_advisor import views


app_name = 'food_advisor'

urlpatterns = [
    path('', views.index, name='index'), # No home page url, index is home page.
    # Uncomment when appropriate views are created.
    path('register/', views.register_user, name='registerUser'),
    path('signin/', views.user_login, name='signin'),
    path('owner/', views.register_manager, name='owner'),
    path('restaurant/<int:restaurant_id_slug>/', views.show_restaurant, name='show_restaurant'),
    path('restaurant/<slug:restaurant_id_slug>/reviews/', views.show_restaurant_reviews, name='show_restaurant_reviews'),
    path('restaurant/<slug:restaurant_id_slug>/reviews/<slug:review_id>', views.review_reply, name='review_reply'),
    path('restaurant/<int:restaurant_id>/manage/', views.manage_restaurant, name='manage_restaurant'),
    path('signout/', views.user_logout, name='signout'),
    path('ajax/add_dish/<int:restaurant_id>/', views.add_dish_ajax, name='add_dish_ajax'),
    path('ajax/delete_dish/<int:dish_id>/', views.delete_dish_ajax, name='delete_dish_ajax'),
]

restaurant_webapp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from food_advisor import views
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('food_advisor/', include('food_advisor.urls')),
    path('admin/', admin.site.urls),
    path('nothing/', views.nothing, name='nothing'),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_advisor/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Dish, UserProfile


from food_advisor.models import CuisineType, Restaurant, Review, STAR_CHOICES

from food_advisor.models import CuisineType, Restaurant

User = get_user_model()



# UserForm for user registration
class UserForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text='Required. Add a valid email address.')

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('email',)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

# ManagerRegistrationForm for manager registration
class ManagerRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text='Required. Add a valid email address.')

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('email',)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.isManager = True  # Ensure your User model supports this attribute
        if commit:
            user.save()
        return user

class RestaurantEditForm(forms.ModelForm):
    name = forms.CharField(max_length=128, label="Name")
    address = forms.CharField(max_length=128, label="Address")
    timeOpens = forms.TimeField(label="Opening Time")
    timeCloses = forms.TimeField(label="Closing Time")
    tags = forms.CharField(max_length=128, label="Tags")
    cuisineTypes = forms.ModelMultipleChoiceField(queryset=CuisineType.objects.all(),
                                                  label="Cuisine Type",
                                                  widget=forms.CheckboxSelectMultiple,)
    image = forms.ImageField(label="Cover Image")

    field_order=['name','address','timeOpens','timeCloses','tags','cuisineTypes','image']

    # An inline class to provide additional information on the form
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Restaurant
        exclude = ('id','manager','starRating','totalReviews',)

#ReviewForm creates reviews from show_restaurant_reviews page
class ReviewForm(forms.ModelForm):
    content = forms.CharField(max_length=1280, label="Content")
    starRating = forms.ChoiceField(choices = STAR_CHOICES, label="Star Rating")

    class Meta:
        model = Review
        exclude = ('id','restaurant','user','date','replyContent')

# LoginForm for user login
class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", required=True)
    password = forms.CharField(label="Password", widget=forms.PasswordInput, required=True)


class ReplyContentForm(forms.ModelForm):
    replyContent = forms.CharField(max_length=1280, label="Owner's Response")

    class Meta:
        model = Review
        fields = ['replyContent']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields= ('isManager',)

class DishForm(forms.ModelForm):
    class Meta:
        model = Dish
        fields = ('name', 'price', 'restaurant')  

    def __init__(self, *args, **kwargs):
        super(DishForm, self).__init__(*args, **kwargs)
        
        self.fields['restaurant'].widget = forms.HiddenInput()

    def save(self, commit=True):
        dish = super().save(commit=False)
        
        if commit:
            dish.save()
        return dish

food_advisor/views.py
import json
from django.http import JsonResponse
from django.conf import settings
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Restaurant, Review, User, Dish, UserProfile, CuisineType
from django.contrib.auth.forms import  AuthenticationForm 
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import DishForm, ManagerRegistrationForm, UserForm, UserProfileForm, ManagerRegistrationForm, RestaurantEditForm, ReviewForm, ReplyContentForm
from django.contrib.auth.forms import UserCreationForm  
from django.shortcuts import render, get_object_or_404

def index(request):
    context_dict = {}
    cuisine_types = CuisineType.objects.all()
    search_query = request.GET.get('search', '')
    filter_query = request.GET.get('filter', '')
    if search_query:
        restaurants = Restaurant.objects.filter(name__icontains=search_query)
        context_dict['prev_search'] = search_query
    elif filter_query and (filter_query != "None"):
        restaurants = Restaurant.objects.filter(cuisineTypes__name__icontains=filter_query)
        context_dict['prev_filter'] = filter_query
    else:
        restaurants = Restaurant.objects.all()
    for restaurant in restaurants:
        restaurant.full_stars = range(restaurant.getIntegerStars())
        restaurant.empty_stars = range(5 - restaurant.getIntegerStars())
    cuisine_types_text = []
    for cuisine_type in cuisine_types:
        cuisine_types_text.append(cuisine_type.name)
    context_dict = context_dict | {'restaurants': restaurants, 'cuisine_types': cuisine_types_text} 
    return render(request, 'food_advisor/index.html', context_dict)

def register_user(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid(): # Save the user's form data to the database. 
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.isManager = False
            profile.save()
            registered = True
            login(request, user)

            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('food_advisor:index')
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'food_advisor/register.html',
                  context = {'user_form': user_form,
                             'profile_form': profile_form,
                             'registered': registered})

@login_required
def manage_restaurant(request, restaurant_id):
    restaurant = get_object_or_404(Restaurant, id=restaurant_id, manager__user=request.user)
    dishes = Dish.objects.filter(restaurant=restaurant)
    
    if request.method == "POST":
        form = RestaurantEditForm(request.POST, request.FILES, instance=restaurant)
        if form.is_valid():
            form.save()
            
            return redirect('food_advisor:show_restaurant', restaurant_id_slug=restaurant.id)
    else:
        form = RestaurantEditForm(instance=restaurant)

    context_dict = {
    'restaurant_form': form,  
    'restaurant': restaurant,
    'dishes': dishes,
}
    return render(request, 'food_advisor/manage_restaurant.html', context_dict)

def register_manager(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        manager_profile_form = UserProfileForm(request.POST)
        restaurant_form = RestaurantEditForm(request.POST, request.FILES)

        if user_form.is_valid() and manager_profile_form.is_valid() and restaurant_form.is_valid(): # Save the user's form data to the database. 
            manager = user_form.save()
            manager_profile = manager_profile_form.save(commit=False)
            manager_profile.user = manager
            manager_profile.isManager = True
            manager_profile.save()
            restaurant_form.instance.manager = manager_profile
            restaurant_form.save()
            registered = True

            login(request, manager)
            return redirect('food_advisor:index')
        else:
            print(user_form.errors, manager_profile_form.errors,restaurant_form.errors)
    else:
        user_form = UserForm()
        manager_profile_form = UserProfileForm()
        restaurant_form = RestaurantEditForm()

    return render(request, 'food_advisor/owner.html',
                  context = {'user_form': user_form,
                             'profile_form': manager_profile_form,
                             'restaurant_form': restaurant_form,
                             'registered': registered})

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request)
        if form.is_valid:

            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    return redirect(reverse('food_advisor:index'))
                else:
                    messages.error(request, "Your foodAdvisor account is disabled.")
            else:
                messages.error(request, "Invalid login details.")
        else:
            messages.error(request, form.errors)
    else:
        form = AuthenticationForm()
                                                # No context variables to pass to the template system, hence the # blank dictionary object...
    return render(request, 'food_advisor/login.html', {'form': form})

def nothing(request):
    return render(request, 'nothing.html')

@login_required
def user_logout(request):
    # Since we know user is logged in, we can simply log them out.
    logout(request)
    return redirect(reverse('food_advisor:index'))

def registerUser(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('food_advisor:index')
    else:
        form = UserCreationForm()
    return render(request, 'food_advisor/register.html', {'form': form})

def registerOwner(request):
    if request.method == 'POST':
        form = ManagerRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('food_advisor:index')
    else:
        form = ManagerRegistrationForm()
    return render(request, 'food_advisor/owner.html', {'form': form})

def nothing(request):
    return render(request, 'nothing.html')
#@login_required
#def restricted(request):
#    return render(request, 'rango/restricted.html')

#@login_required
#def user_logout(request):
 #   logout(request)
  #  return redirect('rango:index')

# A helper method
#def get_server_side_cookie(request, cookie, default_val=None):
 #   val = request.session.get(cookie)
  #  if not val:
   #     val = default_val
#return val
    
def show_restaurant(request, restaurant_id_slug):
    context_dict = {}

    try:
        # Get restaurant from id, if not exists, throw error.
        restaurant = Restaurant.objects.get(id=restaurant_id_slug)
        restaurant.full_stars = range(restaurant.getIntegerStars())
        restaurant.empty_stars = range(5 - restaurant.getIntegerStars())
        # Retrieve all dishes from restaurant.
        dishes = Dish.objects.filter(restaurant=restaurant)

        context_dict['dishes'] = dishes
        context_dict['restaurant'] = restaurant
        context_dict['google_maps_api_key'] = settings.GOOGLE_MAPS_API_KEY

    except Restaurant.DoesNotExist:
        # If don't find restaurant, do nothing.
        context_dict['restaurant'] = None
        context_dict['dishes'] = None
        context_dict['google_maps_api_key'] = None

    # Render response and return it to the client
    return render(request, 'food_advisor/show_restaurant.html', context=context_dict)

def show_restaurant_reviews(request, restaurant_id_slug):
    context_dict = {}
    try:
        restaurant = Restaurant.objects.get(id=restaurant_id_slug)

        reviews = Review.objects.filter(restaurant=restaurant)

        context_dict['reviews'] = reviews
        context_dict['restaurant'] = restaurant
        context_dict['restaurant_id']=restaurant_id_slug

        userNotReviewed = True
        for review in reviews:
            if review.user == request.user:
                userNotReviewed = False
        context_dict['userNotReviewed'] = userNotReviewed

        if request.method == 'POST' and userNotReviewed:
            review_form = ReviewForm(request.POST)
            if review_form.is_valid():
                review = review_form.save(commit=False)
                review.restaurant = restaurant
                review.user = request.user
                review.save()
                new_total_stars = restaurant.totalReviews * restaurant.starRating
                new_total_reviews = restaurant.totalReviews
                new_total_stars += int(review_form.cleaned_data['starRating'])
                new_total_reviews += 1
                restaurant.totalReviews = new_total_reviews
                restaurant.starRating = new_total_stars / new_total_reviews
                restaurant.save()
                return redirect(reverse('food_advisor:show_restaurant_reviews', kwargs={'restaurant_id_slug':restaurant_id_slug}))  
            else:
                print(review_form.errors)
        else:
            review_form = ReviewForm()

templates/food_advisor/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">Login</h3>
                </div>
                <div class="card-body">
                    <form method="post" action="{% url 'food_advisor:signin' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" class="form-control" id="username" name="username" placeholder="Enter username" required>
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" id="password" name="password" placeholder="Password" required>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">Login</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-center">
                    <p>Don't have an account? <a href="{% url 'food_advisor:registerUser' %}">Register here</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/food_advisor/manage_restaurant.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block title %}
    Food Advisor Manager Interface
{% endblock %}

{% block content %}
{% if restaurant %}
    <div class="container mt-5">
        <h2>Manage Restaurant Information</h2>
        <form enctype="multipart/form-data" id="restaurant_manage_form" method="post" action="{% url 'food_advisor:manage_restaurant' restaurant.id %}" class="needs-validation" novalidate>
            {% csrf_token %}
            {% bootstrap_form restaurant_form %}
            <button class="btn btn-primary" type="submit">Update Restaurant Info</button>
        </form>

        <!-- Begin Dish Management Section -->
        <h3 class="mt-5">Manage Dishes</h3>
        <form id="add-dish-form" method="post" action="#" data-restaurant-id="{{ restaurant.id }}"> 
            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="name" class="form-control" placeholder="Dish Name" required />
            </div>
            <div class="form-group">
                <input type="number" name="price" class="form-control" placeholder="Price" required />
            </div>
            <button type="submit" class="btn btn-success">Add Dish</button>
        </form>

        <div id="dishes-list" class="mt-3">
            <h4>Current Menu</h4>
            {% for dish in dishes %}
            <div id="dish-{{ dish.id }}" class="alert alert-secondary d-flex justify-content-between align-items-center mt-2">
                <span>Name: {{ dish.name }}, Price: {{ dish.price }}</span>
                <button class="btn btn-danger delete-dish-button" data-dish-id="{{ dish.id }}">Delete</button>
            </div>
            {% empty %}
            <p>No dishes yet.</p>
            {% endfor %}
        </div>
        <!-- End Dish Management Section -->
    </div>
{% else %}
    <div class="alert alert-danger" role="alert">
        Restaurant does not exist.
    </div>
{% endif %}
{% endblock content %}

{% block script %}
<script src="{% static 'js/dish_script.js' %}"></script>
{% endblock script %}

templates/food_advisor/owner.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block title %}Restaurant Owner{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Restaurant Sign Up</h2>
    <form enctype="multipart/form-data" method="post" action="{% url 'food_advisor:owner' %}">
        <h4>Manager Details</h4>
        {% csrf_token %}
        {% bootstrap_form user_form %}
        <h4>Restaurant Details</h4>
        {% bootstrap_form restaurant_form %}
        <button type="submit" class="btn btn-primary">Create Restaurant</button>
    </form>
    <br>
    <p>Already have an account? <a href="{% url 'food_advisor:signin' %}">Login here</a></p>
</div>
{% endblock content %}

templates/food_advisor/password_reset.html
{% extends "base.html" %}
{% load static %}

{% block title %}Forgot Password{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title text-center">Reset Your Password</h3>
                </div>
                <div class="card-body">
                    <p class="text-center">Enter your email address below and we'll send you a link to reset your password.</p>
                    <form method="post" action="{% url 'food_advisor:password_reset' %}">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email" required>
                        </div>
                        <button type="submit" class="btn btn-primary w-100">Send Reset Link</button>
                    </form>
                </div>
            </div>
            <div class="text-center mt-3">
                <a href="{% url 'food_advisor:signin' %}">Back to Login</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/food_advisor/register.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Sign Up</h2>
    <form method="post" action="{% url 'food_advisor:registerUser' %}">
        {% csrf_token %}
        {% bootstrap_form user_form %}
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
    <br>
    <p>Already have an account? <a href="{% url 'food_advisor:signin' %}">Login here</a></p>
</div>
{% endblock content %}

templates/food_advisor/review_reply.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}


{% block title %}
    Review Reply Form
{% endblock title %}

{% block content %}
    <div class="container mt-5">
        <div class="card mb-3">
            <div class="card-body">
                {% with ''|center:review.starRating as range %}
                {% for _ in range %}
                    <img src="{% static 'images/star.png' %}" class="img-fluid" style="height: 25px;">
                {% endfor %}
                {% endwith %}
                <br /><br />
                <p class="card-text">{{ review.content }}</p>
                <p class="card-text">User: {{ review.user }}</p>
                <p class="card-text">Posted at: {{ review.date }}</p>
            </div>
        </div>
    </div>

    <div class="container mt-5">
        <form enctype="multipart/form-data" method="post" action="{% url 'food_advisor:review_reply' restaurant_id_slug=restaurant_id review_id=review.id %}">
            {% csrf_token %}
            {% bootstrap_form review_form %}
            <button  type="submit" class="btn btn-primary">Submit Response</button>
        </form>
    </div>
{% endblock content %}

templates/food_advisor/reviews.html
<!DOCTYPE html>

{% extends "base.html" %}
    
{% block title %}
    {% if Restaurant %}
        {{ restaurant.name}}
    {% else %}
        {{ Unknown Restaurant }}
{% endblock %}

{% block content %}
<div class="container mt-5">    
    <h1>Reviews</h1>
    {% if reviews %} 
        {% for r in reviews %}
        <div>
            <p> User: {{ r.user }}</p>
            <p><strong>{{ r.content }}</strong></p>
            <p>Date: {{ reviews.date }}</p>
            <p>Star Rating: {{ r.starRating }}</p>
            {% if r.replyContent %}
                <p>Reply: <strong>{{ r.replyContent }}</strong></p>
            {% endif %}
        </div>
    {% endfor %}
    {% else %}
        This restaurant has no reviews yet. Be the first!
    {% endif %}
</div>
{% endblock %}

templates/food_advisor/show_restaurant.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Food Advisor - {{ restaurant.name }}
{% endblock %}

{% block content %}
<div class="container my-5">
    {% if restaurant %}
    <h1 class="display-4 text-center mb-3">{{ restaurant.name }}</h1>

    {% if user.is_authenticated and user == restaurant.manager.user %}
    <p class="text-center mb-3" style="color:#a32410">You are this restaurant's manager.</p>
    {% endif %}

    <div id="star-block" class="text-center mb-3">
        {% for star in restaurant.full_stars %}
            <span class="fas fa-star"></span> <!-- full stars -->
        {% endfor %}
        {% for star in restaurant.empty_stars %}
            <span class="far fa-star"></span> <!-- empty stars -->
        {% endfor %}
        <p class="lead">Average Star Rating: {{ restaurant.starRating|floatformat:2 }}</p>
    </div>

    <div id="image-block" class="text-center mb-3">
        {% if restaurant.image %}
        <img src="{{ restaurant.image.url }}" class="img-fluid rounded" alt="{{ restaurant.name }}">
        {% else %}
        <img src="{% static 'images/1.jpg' %}" class="img-fluid rounded" alt="{{ restaurant.name }}" style="width: 800px; height: auto;">
        {% endif %}
    </div>

        
    <div id="reviews-link-block" class="text-center mb-3">
        <h3><a href="{% url 'food_advisor:show_restaurant_reviews' restaurant.id %}" class="btn btn-primary">View Reviews ({{ restaurant.totalReviews }})</a></h3>
    </div>

    <div id="address-block" class="mb-3">
        <h3>Address</h3>
        <p>{{ restaurant.address }}</p>
    </div>

    <div id="map" style="height: 400px;"></div>

    <div id="hours-block" class="mb-3">
        <h3>Opening Hours</h3>
        <p>{{ restaurant.timeOpens|time:"G:i"}} - {{ restaurant.timeCloses|time:"G:i" }}</p>
    </div>

    <div id="tags-block" class="mb-3">
        <h3>Tags</h3>
        <p>
            {% for tag in restaurant.getTags %}
            <span class="badge badge-secondary">{{ tag }}</span>
            {% endfor %}
        </p>
    </div>

    <div id="cuisine-type-block" class="mb-3">
        <h3>Cuisine Type</h3>
        {% if restaurant.cuisineTypes.all %}
        {% for cuisine in restaurant.cuisineTypes.all %}
        <p>{{ cuisine.name }}</p>
        {% endfor %}
        {% else %}
        <p>No cuisine type available.</p>
        {% endif %}
    </div>

    <div id="menu-block" class="mb-5">
        <h3>Menu</h3>
        {% if dishes %}
        <ul class="list-group">
            {% for dish in dishes %}
            <li class="list-group-item d-flex justify-content-between align-items-center" id="dish-{{ dish.id }}">
                {{ dish.name }}
                <span class="badge badge-primary badge-pill">£{{ dish.price }}</span>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <div class="alert alert-warning" role="alert">No menu available.</div>
        {% endif %}
    </div>

    {% if user.is_authenticated and user == restaurant.manager.user %}
    <div class="text-center mb-3">
        <a href="{% url 'food_advisor:manage_restaurant' restaurant.id %}" class="btn btn-info">Manage Restaurant Info</a>
    </div>
    {% endif %}
    {% else %}
    <div class="alert alert-danger" role="alert">
        The specified restaurant does not exist.
    </div>
    {% endif %}
</div>

<script>
function initMap() {
    var geocoder = new google.maps.Geocoder();
    var address = '{{ restaurant.address }}';

    geocoder.geocode({ 'address': address }, function(results, status) {
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15,
            center: {lat: -34.397, lng: 150.644} // default center if geocoding fails
        });

        if (status === 'OK' && results && results[0]) {
            var marker = new google.maps.Marker({  map: map,
                position: results[0].geometry.location,
                title: '{{ restaurant.name }}'
            });
            map.setCenter(results[0].geometry.location);
        } else {
            console.error('Geocode was not successful for the following reason: ' + status);
        }
    });
}
</script>

<script async defer src="https://maps.googleapis.com/maps/api/js?key={{ google_maps_api_key }}&callback=initMap"></script>

{% endblock content %}

templates/food_advisor/show_restaurant_reviews.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}


{% block title %}
    Reviews for {{ restaurant.name }}
{% endblock title %}

{% block content %}
    <div class="container mt-5">
        <h2>Reviews for {{ restaurant.name }}</h2>
        {% if reviews %}
            <div class="row">
                {% for review in reviews %}
                    <div class="col-md-6">
                        <div class="card mb-3">
                            <div class="card-body">
                                {% with ''|center:review.starRating as range %}
                                {% for _ in range %}
                                    <img src="{% static 'images/star.png' %}" class="img-fluid" style="height: 25px;">
                                {% endfor %}
                                {% endwith %}
                                <br /><br />
                                <p class="card-text">{{ review.content }}</p>
                                <p class="card-text">User: {{ review.user }}</p>
                                <p class="card-text">Posted at: {{ review.date }}</p>
                                {% if review.replyContent %}
                                <p class="card-text">Owner's Response: {{review.replyContent }}</p>
                                {% endif %}
                                {% if user.is_authenticated and user == restaurant.manager.user %}
                                    <a href="{% url 'food_advisor:review_reply' restaurant_id_slug=restaurant.id review_id=review.id %}" class="btn btn-primary">Reply</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>No reviews available for this restaurant.</p>
        {% endif %}
    </div>

    <div class="container mt-5">
        {% if user.is_authenticated and not user.user_profile.isManager %}
            {% if userNotReviewed %}
                <form method="post" action="{% url 'food_advisor:show_restaurant_reviews' restaurant_id_slug=restaurant_id %}">
                    {% csrf_token %}
                    <input type="hidden" name="restaurant_id" value="{{ restaurant_id }}">
                    <input type="hidden" name="user" value="{{ user.id }}">
                    {% bootstrap_form review_form %}
                    <button type="submit" class="btn btn-primary">Submit Review</button>
                </form>
            {% else %}
                <p>You have already reviewed this restaurant.</p>
            {% endif %}
        {% endif %}
    </div>

{% endblock content %}